### ISSUE TITLE
Redux setup is not correct

### ISSUE THREAD

**Issue by markerikson** [sachie/react-quickstart#16]
Unfortunately, the Redux setup in this example project is not correct. It's still using the legacy Redux `createStore` API, using "hand-written" reducer logic with separate action constants, and following an outdated folder structure.  Today we teach and recommend using "modern Redux" using our official Redux Toolkit package, the React-Redux hooks API, and a "feature folder" structure with a single "slice" file of Redux logic per feature.

Please see the "Redux Essentials" tutorial and the Redux Style Guide best practices page in our docs for our recommended approaches:

- https://redux.js.org/tutorials/index
- https://redux.js.org/style-guide/style-guide

**Comment by sachie** [comment]
@markerikson Thanks for bringing this to my attention. The new setup seems far neater to use!
I have removed the old redux structure and added an example with redux-toolkit in #17.

**Comment by markerikson** [comment]
Great, thanks!
